# Generated by Django 3.2.6 on 2021-09-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_token_publishing_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
