# Generated by Django 3.2.7 on 2021-09-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0004_usermanage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManage',
        ),
    ]
