# Generated by Django 3.2.7 on 2021-09-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0006_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
