# Generated by Django 3.2.7 on 2021-09-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0007_token_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
