# Generated by Django 3.2.7 on 2021-09-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0008_auto_20210925_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preuser',
            old_name='user',
            new_name='username',
        ),
    ]
